### ISSUE TITLE
There appear to be 1 leaked semaphore objects to clean up at shutdown

### ISSUE THREAD

**Issue by RabiyaF** [mlco2/codecarbon#720]
* CodeCarbon version: 2.8.0
* Python version: 3.10.15
* Operating System: Mac OS (Sequoia)

### Description

We were using codecarbon **2.6.0** for [fitbenchmarking](https://github.com/fitbenchmarking/fitbenchmarking) and this was working fine. 

We then updated to **2.7.1** and were seeing the`"EmissionsTracker" object has no attribute '_scheduler'` error.

Today, I updated the codecarbon dependency to test the latest version **2.8.0**. Everything seems to work okay. But if I do a `KeyboardInterrupt`, I see the following warning:

```
UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

If I downgrade to codecarbon **2.6.0** and do a `KeyboardInterrupt` I do not see this warning. I see the normal stack trace of the `KeyboardInterrupt`.

**Question:** Has something been updated recently that might be causing this warning ?

**Comment by benoit-cty** [comment]
Hello,
Thanks for reporting this and using CodeCarbon.

It may have been introduced by https://github.com/mlco2/codecarbon/pull/701/files
Maybe it is because the scheduler is not stopped properly in this case ? @inimaz do you have an idea ?

But I don't see the message you mention when I do a Ctrl+C, can you tell me more on how you get it ?

**Comment by inimaz** [comment]
Hi! 
Thanks for using Codecarbon!
Indeed as @benoit-cty  suggested it could be this feature.  Could you provide a snippet of how you are using codecarbon + some more logs? Otherwise I think it is hard to tell. 
Thanks!
